[package]
name = "dsp"
version = "0.1.0"
edition = "2021"
[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = [
    "assert_process_allocs",
    "standalone",
] }
circular-buffer = "0.1.6"
