// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Action = { "type": "Ratio", value: number, } | { "type": "Threshold", value: number, } | { "type": "AttackTime", value: number, } | { "type": "ReleaseTime", value: number, } | { "type": "KneeWidth", value: number, } | { "type": "InputGain", value: number, } | { "type": "OutputGain", value: number, } | { "type": "DryWet", value: number, };
