// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Amplitude = { pre_amplitude: number, post_amplitude: number, amt_reduced: number, };
