// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amplitude } from "./Amplitude";
import type { Parameter } from "./Parameter";

export type Message =
  | "Init"
  | "WindowClosed"
  | { ParameterUpdate: Parameter }
  | { Amplitude: Amplitude };
