// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParameterEvent = { "parameter": "Ratio", value: number, } | { "parameter": "Threshold", value: number, } | { "parameter": "AttackTime", value: number, } | { "parameter": "ReleaseTime", value: number, } | { "parameter": "KneeWidth", value: number, } | { "parameter": "InputGain", value: number, } | { "parameter": "OutputGain", value: number, } | { "parameter": "DryWet", value: number, };
