// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Parameter = { "Ratio": number } | { "Threshold": number } | { "AttackTime": number } | { "ReleaseTime": number } | { "KneeWidth": number } | { "InputGain": number } | { "OutputGain": number } | { "DryWet": number } | { "RmsBufferSize": number } | { "Lookahead": number } | { "RmsMix": number };
