// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginMessage = { "type": "ParamChange", param: string, value: number, } | { "type": "PeakMeterData", value: number, };
